# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7233a532e137176f140e1dcd56aca5fd862109d2338f5b0431ec709bb3e8dd155f7e40d68012784e84e3a015b27fbb7ac18e3da75fc4e94329116693b219517c

test:
  secret_key_base: 7d2c8bf8d185300d8df5b74326734ab85df28e7cb0a5a50507e96c6fa996a1cefa8f795558157018bd5ce6d937d17847fe72804eba9593ee91bf68e625c58987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
